export interface CategoryQuestionStat {
  id: string;
  code: string;
  name: string;
  count: number;
  weighting: 'High' | 'Medium' | 'Low';
  bnfChapter: string;
  description: string;
  keyTopics: string[];
  subtopics?: { id: string; name: string; count: number }[];
  status?: 'live' | 'authoring';
}

export interface QuestionInventory {
  totalLiveCount: number;
  badgeLabel: string;
  marketingHeadline: string;
  categories: CategoryQuestionStat[];
}

/**
 * Single source of truth for all AcePharm question inventory and counts.
 * Synchronizes the marketing site, pricing matrix, learner dashboard, and session builder.
 * Total verified live questions: 1,905 across all 19 GPhC syllabus categories.
 */
export const QUESTION_INVENTORY: QuestionInventory = {
  totalLiveCount: 1905,
  badgeLabel: '1,905 High-Yield Questions Live',
  marketingHeadline: '1,905 authentic revision scenarios available',
  categories: [
    {
      id: 'cat-cv',
      code: 'cardiovascular',
      name: 'Cardiovascular System',
      count: 160,
      weighting: 'High',
      bnfChapter: 'BNF Chapter 2',
      description: 'Hypertension, heart failure, arrhythmias, anticoagulation, lipid modification and acute coronary syndromes.',
      keyTopics: ['NICE NG136', 'DOAC Dosing', 'Heart Failure Stepwise Therapy', 'Warfarin & INR Monitoring', 'Acute Coronary Syndromes'],
      subtopics: [
        { id: 'sub-htn', name: 'Hypertension Guidelines (NICE NG136)', count: 40 },
        { id: 'sub-hf', name: 'Heart Failure HFrEF Quad Therapy', count: 35 },
        { id: 'sub-af', name: 'Atrial Fibrillation & Anticoagulation (DOACs)', count: 35 },
        { id: 'sub-lipid', name: 'Lipid Modification & Statin Titration', count: 25 },
        { id: 'sub-acs', name: 'Acute Coronary Syndromes & DAPT Protocols', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-calc',
      code: 'calculations',
      name: 'Pharmaceutical Calculations (Paper 1)',
      count: 180,
      weighting: 'High',
      bnfChapter: 'GPhC Paper 1 Focus',
      description: 'Dosages, dilution, concentrations, infusion rates, molecular weights, displacement volumes and pharmacokinetics.',
      keyTopics: ['Cockcroft-Gault CrCl', 'IV Infusions & Drop Rates', 'Displacement Volumes', 'Dilutions & Alligations', 'Paediatric BSA Dosing'],
      subtopics: [
        { id: 'sub-crcl', name: 'Cockcroft-Gault Creatinine Clearance', count: 45 },
        { id: 'sub-infusions', name: 'IV Infusions & Drop Rates', count: 40 },
        { id: 'sub-displacements', name: 'Displacement Volumes & Reconstitution', count: 35 },
        { id: 'sub-dilutions', name: 'Dilutions, Alligation & Concentrations', count: 30 },
        { id: 'sub-paed-dose', name: 'Paediatric & Surface Area Dosing', count: 30 },
      ],
      status: 'live',
    },
    {
      id: 'cat-cns',
      code: 'cns',
      name: 'Central Nervous System',
      count: 155,
      weighting: 'High',
      bnfChapter: 'BNF Chapter 4',
      description: 'Depression, anxiety, psychosis, Parkinson’s disease, epilepsy management, and substance misuse services.',
      keyTopics: ['Valproate Pregnancy Prevention', 'Lithium Toxicity & TDM', 'Antidepressant Switching', 'Parkinsonian Motor Symptoms', 'Substance Misuse'],
      subtopics: [
        { id: 'sub-epilepsy', name: 'Epilepsy & Valproate Safety Measures', count: 35 },
        { id: 'sub-depression', name: 'Depression, SSRIs & Serotonin Syndrome', count: 35 },
        { id: 'sub-lithium', name: 'Bipolar Disorder & Lithium Toxicity TDM', count: 30 },
        { id: 'sub-parkinson', name: 'Parkinson’s Disease Timing & Dopamine Agonists', count: 30 },
        { id: 'sub-substance', name: 'Substance Misuse & Supervised Consumption', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-infections',
      code: 'infections',
      name: 'Infections & Antimicrobial Stewardship',
      count: 145,
      weighting: 'High',
      bnfChapter: 'BNF Chapter 5',
      description: 'Antibiotic selection, sepsis screening, UKHSA primary care guidance, antifungal and antiviral regimens.',
      keyTopics: ['Gentamicin & Vancomycin TDM', 'UKHSA Stewardship Guidance', 'Penicillin Allergy Stratification', 'Clostridioides difficile', 'Community-Acquired Pneumonia'],
      subtopics: [
        { id: 'sub-uti', name: 'Urinary Tract Infections (NICE & UKHSA)', count: 35 },
        { id: 'sub-cap', name: 'Community-Acquired Pneumonia (CURB-65)', count: 35 },
        { id: 'sub-tdm', name: 'Therapeutic Drug Monitoring: Gentamicin & Vancomycin', count: 25 },
        { id: 'sub-cdiff', name: 'Clostridioides difficile Protocols', count: 25 },
        { id: 'sub-allergy', name: 'Penicillin Allergy Stratification', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-resp',
      code: 'respiratory',
      name: 'Respiratory System',
      count: 140,
      weighting: 'High',
      bnfChapter: 'BNF Chapter 3',
      description: 'Asthma and COPD management guidelines, inhaler device technique, and acute exacerbation protocols.',
      keyTopics: ['BTS/SIGN Guidelines', 'GOLD COPD Criteria', 'Inhaler Technique Calibration', 'Acute Asthma Emergency Protocols'],
      subtopics: [
        { id: 'sub-asthma', name: 'Asthma BTS/SIGN Stepwise Therapy', count: 45 },
        { id: 'sub-copd', name: 'COPD Maintenance & Inhalers (GOLD/NICE)', count: 35 },
        { id: 'sub-inhaler-tech', name: 'Inhaler Technique & Device Selection', count: 35 },
        { id: 'sub-acute-asthma', name: 'Acute Asthma Emergency Management', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-endocrine',
      code: 'endocrine',
      name: 'Endocrine & Diabetes',
      count: 130,
      weighting: 'High',
      bnfChapter: 'BNF Chapter 6',
      description: 'Type 1 and Type 2 Diabetes regimens, thyroid disease, corticosteroids, and adrenal crisis management.',
      keyTopics: ['NICE NG28 Glycaemic Algorithms', 'Insulin Safety & Sick Day Rules', 'Steroid Emergency Cards', 'Hypo- and Hyperthyroidism'],
      subtopics: [
        { id: 'sub-t2dm', name: 'Type 2 Diabetes Pharmacotherapy (NICE NG28)', count: 45 },
        { id: 'sub-insulin', name: 'Insulin Regimens & Sick Day Rules', count: 35 },
        { id: 'sub-thyroid', name: 'Hypo- and Hyperthyroidism Management', count: 25 },
        { id: 'sub-steroids', name: 'Steroid Emergency Card & Adrenal Crisis', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-law',
      code: 'pharmacy-law',
      name: 'Pharmacy Law, Ethics & Practice',
      count: 120,
      weighting: 'High',
      bnfChapter: 'Medicines Ethics & Practice (MEP)',
      description: 'Controlled Drugs schedules, emergency supplies, responsible pharmacist regulations, and fitness to practise.',
      keyTopics: ['Misuse of Drugs Regs 2001', 'Responsible Pharmacist 2hr Absence', 'Emergency Supply Rules', 'Veterinary Cascade Regulations'],
      subtopics: [
        { id: 'sub-cd', name: 'Controlled Drugs Schedules & Prescriptions', count: 35 },
        { id: 'sub-rp', name: 'Responsible Pharmacist Regulations & Absence', count: 35 },
        { id: 'sub-emergency', name: 'Emergency Supplies at Request of Patient/Doctor', count: 25 },
        { id: 'sub-vet', name: 'Veterinary Prescriptions & Cascade Regulations', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-otc-first',
      code: 'pharmacy-first',
      name: 'Pharmacy First & OTC Consultations',
      count: 105,
      weighting: 'High',
      bnfChapter: 'NHS England Pharmacy First',
      description: 'Clinical pathways for the 7 common conditions under NHS Pharmacy First, red flags, and community pharmacy triage.',
      keyTopics: ['Uncomplicated UTI Protocol', 'FeverPAIN & Centor Sore Throat', 'Acute Otitis Media', 'Infective Skin Conditions'],
      subtopics: [
        { id: 'sub-uti-first', name: 'Uncomplicated UTI Clinical Pathway', count: 30 },
        { id: 'sub-throat-first', name: 'Sore Throat (FeverPAIN / Centor)', count: 30 },
        { id: 'sub-otitis-first', name: 'Acute Otitis Media Diagnostic Triage', count: 25 },
        { id: 'sub-impetigo-first', name: 'Infective Skin Conditions (Impetigo/Shingles)', count: 20 },
      ],
      status: 'live',
    },
    {
      id: 'cat-gastro',
      code: 'gastrointestinal',
      name: 'Gastrointestinal System',
      count: 95,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 1',
      description: 'Dyspepsia, peptic ulcer disease, inflammatory bowel disease (IBD), stoma care, and liver impairment.',
      keyTopics: ['H. pylori Triple Eradication', 'PPI Long-Term Risks', 'IBD 5-ASA & Biologics', 'Portal Hypertension & Cirrhosis'],
      subtopics: [
        { id: 'sub-gerd', name: 'GORD, Peptic Ulcers & H. pylori', count: 40 },
        { id: 'sub-ibd', name: 'Inflammatory Bowel Disease & 5-ASA', count: 30 },
        { id: 'sub-liver', name: 'Hepatic Impairment & Portal Hypertension', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-musculo',
      code: 'musculoskeletal',
      name: 'Musculoskeletal & Joint Diseases',
      count: 90,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 10',
      description: 'Rheumatoid arthritis, gout, osteoarthritis, DMARD monitoring, and NSAID safety profiles.',
      keyTopics: ['Allopurinol Titration in Gout', 'Methotrexate Toxicity & Blood Monitoring', 'Bisphosphonate Administration Protocols'],
      subtopics: [
        { id: 'sub-gout', name: 'Acute Gout & Allopurinol Titration', count: 35 },
        { id: 'sub-ra', name: 'Rheumatoid Arthritis & Methotrexate Monitoring', count: 30 },
        { id: 'sub-osteo', name: 'Osteoporosis & Bisphosphonate Counselling', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-derm',
      code: 'dermatology',
      name: 'Dermatology & Skin Conditions',
      count: 85,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 13',
      description: 'Eczema, psoriasis, topical corticosteroid potencies, acne regimens, and skin infection recognition.',
      keyTopics: ['Fingertip Units (FTU)', 'Topical Corticosteroid Potency Ladder', 'Oral Isotretinoin Pregnancy Prevention (PPP)'],
      subtopics: [
        { id: 'sub-eczema', name: 'Atopic Eczema & Topical Corticosteroid Ladders', count: 35 },
        { id: 'sub-psoriasis', name: 'Psoriasis Topicals & Systemics', count: 25 },
        { id: 'sub-acne', name: 'Acne Vulgaris & Oral Isotretinoin PPP', count: 25 },
      ],
      status: 'live',
    },
    {
      id: 'cat-gu',
      code: 'genito-urinary',
      name: 'Genito-Urinary & Renal Medicine',
      count: 80,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 7',
      description: 'Urinary tract infections, benign prostatic hyperplasia, acute kidney injury (DAMN drugs), and emergency contraception.',
      keyTopics: ['Emergency Hormonal Contraception (LNG vs UPA)', 'BPH Alpha-Blockers & 5-ARIs', 'Acute Kidney Injury (DAMN Drugs)'],
      subtopics: [
        { id: 'sub-bph', name: 'Benign Prostatic Hyperplasia (BPH)', count: 30 },
        { id: 'sub-contraception', name: 'Emergency Hormonal Contraception (LNG vs UPA)', count: 30 },
        { id: 'sub-aki', name: 'Acute Kidney Injury (DAMN Drugs)', count: 20 },
      ],
      status: 'live',
    },
    {
      id: 'cat-malignancy',
      code: 'malignancy',
      name: 'Malignant Disease & Immunosuppression',
      count: 75,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 8',
      description: 'Cytotoxic chemotherapy safety, monoclonal antibodies, extravasation protocols, and antiemetic regimens.',
      keyTopics: ['Neutropenic Sepsis Emergency', 'Oral Anticancer Safety & Extravasation', 'Chemotherapy-Induced Nausea & Vomiting'],
      subtopics: [
        { id: 'sub-oral-chemo', name: 'Oral Anticancer Safety & Extravasation', count: 30 },
        { id: 'sub-neutropenia', name: 'Febrile Neutropenia Emergency', count: 25 },
        { id: 'sub-chemo-emesis', name: 'Antiemetic Regimens in Cytotoxics', count: 20 },
      ],
      status: 'live',
    },
    {
      id: 'cat-blood',
      code: 'blood-nutrition',
      name: 'Blood & Nutrition',
      count: 75,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 9',
      description: 'Anaemia management, electrolyte disturbances, oral vs IV iron formulations, and vitamin D deficiency.',
      keyTopics: ['Oral Iron Alternate-Day Dosing', 'Electrolyte Disturbances & IV Fluids', 'Vitamin D High-Dose Loading Regimens'],
      subtopics: [
        { id: 'sub-anaemia', name: 'Iron Deficiency & Oral Replacement', count: 30 },
        { id: 'sub-electrolytes', name: 'Potassium & Sodium Electrolyte Disturbances', count: 25 },
        { id: 'sub-vit-d', name: 'Vitamin D Deficiency Treatment Protocols', count: 20 },
      ],
      status: 'live',
    },
    {
      id: 'cat-obs-gyn',
      code: 'obstetrics-gynaecology',
      name: 'Obstetrics, Gynaecology & Breastfeeding',
      count: 65,
      weighting: 'Medium',
      bnfChapter: 'BNF Chapter 7 & BUMPS',
      description: 'Prescribing safely in pregnancy, drug transfer into breast milk, HRT regimens, and teratogenic risk management.',
      keyTopics: ['Hypertension in Pregnancy (Labetalol)', 'Teratogenic Medications (ACEi, Retinoids)', 'HRT Regimens & VTE Risks'],
      subtopics: [
        { id: 'sub-pregnancy-drugs', name: 'Teratogenic Medications & Prescribing in Pregnancy', count: 25 },
        { id: 'sub-lactation', name: 'Drug Transfer into Breast Milk', count: 20 },
        { id: 'sub-hrt', name: 'HRT Regimens & Venous Thromboembolism Risks', count: 20 },
      ],
      status: 'live',
    },
    {
      id: 'cat-ent',
      code: 'ent',
      name: 'Ear, Nose & Oropharynx',
      count: 60,
      weighting: 'Low',
      bnfChapter: 'BNF Chapter 12',
      description: 'Otitis externa with tympanic perforation, allergic rhinitis, rhinitis medicamentosa, and oral candidiasis.',
      keyTopics: ['Non-Ototoxic Ear Drops (Ciprofloxacin)', 'Rhinitis Medicamentosa Rebound', 'Oral Candidiasis Management'],
      subtopics: [
        { id: 'sub-otitis-externa', name: 'Otitis Externa & Perforated Eardrum', count: 25 },
        { id: 'sub-allergic-rhinitis', name: 'Allergic Rhinitis & Nasal Decongestant Rebound', count: 20 },
        { id: 'sub-oral-candida', name: 'Oral Candidiasis & Inhaled Corticosteroids', count: 15 },
      ],
      status: 'live',
    },
    {
      id: 'cat-eye',
      code: 'ophthalmology',
      name: 'Eye Conditions & Ophthalmology',
      count: 55,
      weighting: 'Low',
      bnfChapter: 'BNF Chapter 11',
      description: 'Glaucoma topical therapies, ocular beta-blocker contraindications in asthma, red eye triage, and dry eye disease.',
      keyTopics: ['Prostaglandin Analogues vs Beta-Blockers', 'Ocular Timolol Asthma Contraindication', 'Dry Eye Preservative-Free Drops'],
      subtopics: [
        { id: 'sub-glaucoma', name: 'Open-Angle Glaucoma Topicals & Contraindications', count: 25 },
        { id: 'sub-red-eye', name: 'Red Eye Triage & Bacterial Conjunctivitis', count: 15 },
        { id: 'sub-dry-eye', name: 'Dry Eye Disease & Preservative-Free Lubricants', count: 15 },
      ],
      status: 'live',
    },
    {
      id: 'cat-anaesthesia',
      code: 'anaesthesia',
      name: 'Anaesthesia & Intensive Care',
      count: 50,
      weighting: 'Low',
      bnfChapter: 'BNF Chapter 15',
      description: 'Local anaesthetics maximum safe doses, adrenaline contraindications in end-arteries, and perioperative drug pauses.',
      keyTopics: ['Plain vs Adrenaline Lidocaine End-Artery Necrosis', 'Local Anaesthetic Systemic Toxicity (LAST)', 'Preoperative Medication Pauses'],
      subtopics: [
        { id: 'sub-local-anaesthetic', name: 'Local Anaesthetics & Maximum Dosing', count: 20 },
        { id: 'sub-preop-pauses', name: 'Perioperative Medication Management', count: 15 },
        { id: 'sub-malignant-hyp', name: 'Malignant Hyperthermia & Dantrolene Protocol', count: 15 },
      ],
      status: 'live',
    },
    {
      id: 'cat-poisoning',
      code: 'poisoning-emergency',
      name: 'Emergency Treatment of Poisoning',
      count: 40,
      weighting: 'Low',
      bnfChapter: 'BNF Treatment Summaries',
      description: 'Paracetamol overdose nomogram vs staggered ingestions, specific antidotes (naloxone, flumazenil), and salicylate toxicity.',
      keyTopics: ['Staggered Paracetamol Overdose Acetylcysteine Decision', 'Opioid Overdose Naloxone Titration', 'Salicylate Toxicity Urine Alkalinisation'],
      subtopics: [
        { id: 'sub-paracetamol-tox', name: 'Paracetamol Overdose & Acetylcysteine', count: 20 },
        { id: 'sub-antidotes', name: 'Specific Antidotes (Naloxone, Flumazenil, Digibind)', count: 10 },
        { id: 'sub-salicylate-tox', name: 'Salicylate Overdose & Urinary Alkalinisation', count: 10 },
      ],
      status: 'live',
    },
  ],
};
